#!/bin/bash
# Bastion TUI - Network Library
# Solana RPC calls, network management, and pool data

# ═══════════════════════════════════════════════════════════════════
# Configuration (defaults, overridden by contracts.env)
# ═══════════════════════════════════════════════════════════════════
SOLANA_RPC_URL="${SOLANA_RPC_URL:-http://127.0.0.1:8899}"
CHAIN_NAME="${CHAIN_NAME:-solana-localnet}"

# Program IDs (from config)
BASTION_POOL_PROGRAM="${BASTION_POOL_PROGRAM:-CbHS6twCMkYyodaEUtvonRV6HVBZnkGjekohLqXJziU5}"
BASTION_AMM_PROGRAM="${BASTION_AMM_PROGRAM:-BvFgtfCEeCcMHoN1PRHSXkdzVYTka1NsrVBTeHmnDN2D}"
USDC_MINT="${USDC_MINT:-EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v}"
WSOL_MINT="${WSOL_MINT:-So11111111111111111111111111111111111111112}"

# ═══════════════════════════════════════════════════════════════════
# Network Auto-Detection
# ═══════════════════════════════════════════════════════════════════

detect_network() {
    # Auto-detect from solana config if available
    if command -v solana &>/dev/null; then
        local rpc
        rpc=$(solana config get 2>/dev/null | grep "RPC URL" | awk '{print $NF}')
        if [[ -n "$rpc" ]]; then
            SOLANA_RPC_URL="$rpc"
            case "$rpc" in
                *"127.0.0.1"*|*"localhost"*)
                    CHAIN_NAME="solana-localnet" ;;
                *"devnet"*)
                    CHAIN_NAME="solana-devnet" ;;
                *"mainnet"*)
                    CHAIN_NAME="solana-mainnet" ;;
                *)
                    CHAIN_NAME="solana-custom" ;;
            esac
        fi
    fi
}

# Switch to a specific network
switch_network() {
    local network="$1"  # localnet, devnet, mainnet

    local config_dir
    config_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/config"

    # Source network profiles
    if [[ -f "$config_dir/networks.env" ]]; then
        source "$config_dir/networks.env"
    fi

    case "$network" in
        localnet|local)
            SOLANA_RPC_URL="$LOCALNET_RPC"
            CHAIN_NAME="$LOCALNET_LABEL"
            BASTION_POOL_PROGRAM="$LOCALNET_POOL_PROGRAM"
            BASTION_AMM_PROGRAM="$LOCALNET_AMM_PROGRAM"
            ;;
        devnet|dev)
            SOLANA_RPC_URL="$DEVNET_RPC"
            CHAIN_NAME="$DEVNET_LABEL"
            BASTION_POOL_PROGRAM="$DEVNET_POOL_PROGRAM"
            BASTION_AMM_PROGRAM="$DEVNET_AMM_PROGRAM"
            ;;
        mainnet|main)
            SOLANA_RPC_URL="$MAINNET_RPC"
            CHAIN_NAME="$MAINNET_LABEL"
            BASTION_POOL_PROGRAM="$MAINNET_POOL_PROGRAM"
            BASTION_AMM_PROGRAM="$MAINNET_AMM_PROGRAM"
            ;;
        *)
            return 1 ;;
    esac

    # Persist to contracts.env
    cat > "$config_dir/contracts.env" << EOF
# Bastion Contract Configuration
# Auto-generated by network switcher

CHAIN_NAME=$CHAIN_NAME
SOLANA_RPC_URL=$SOLANA_RPC_URL

# Deployed Program IDs
BASTION_POOL_PROGRAM=$BASTION_POOL_PROGRAM
BASTION_AMM_PROGRAM=$BASTION_AMM_PROGRAM

# Token Mints
USDC_MINT=$USDC_MINT
WSOL_MINT=$WSOL_MINT
EOF

    # Also update solana CLI config if available
    if command -v solana &>/dev/null; then
        solana config set --url "$SOLANA_RPC_URL" &>/dev/null || true
    fi

    return 0
}

# ═══════════════════════════════════════════════════════════════════
# Solana JSON-RPC Helper
# ═══════════════════════════════════════════════════════════════════
rpc_call() {
    local method="$1"
    local params="$2"
    local timeout="${3:-5}"

    curl -s --max-time "$timeout" -X POST "$SOLANA_RPC_URL" \
        -H "Content-Type: application/json" \
        -d "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"$method\",\"params\":$params}" 2>/dev/null
}

# ═══════════════════════════════════════════════════════════════════
# Network Status
# ═══════════════════════════════════════════════════════════════════
get_block_height() {
    local result

    # Try solana CLI first (fastest)
    if command -v solana &>/dev/null; then
        result=$(timeout 3 solana slot --url "$SOLANA_RPC_URL" 2>/dev/null) || true
        if [[ "$result" =~ ^[0-9]+$ ]]; then
            echo "$result"
            return
        fi
    fi

    # Fallback to RPC
    result=$(rpc_call "getSlot" "[]" 3)
    echo "$result" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('result', 'N/A'))
except:
    print('N/A')
" 2>/dev/null || echo "N/A"
}

check_connection() {
    local result

    result=$(rpc_call "getHealth" "[]" 3 2>/dev/null) || true

    if echo "$result" | grep -q '"ok"' 2>/dev/null; then
        echo "connected"
        return
    fi

    # Fallback: try getSlot
    result=$(rpc_call "getSlot" "[]" 3 2>/dev/null) || true
    if echo "$result" | grep -q '"result"' 2>/dev/null; then
        echo "connected"
    else
        echo "disconnected"
    fi
}

# ═══════════════════════════════════════════════════════════════════
# Account Functions
# ═══════════════════════════════════════════════════════════════════
get_pubkey_from_keypair() {
    local keypair_file="$1"

    if command -v solana-keygen &>/dev/null; then
        solana-keygen pubkey "$keypair_file" 2>/dev/null
    else
        # Fallback: parse JSON array
        python3 -c "
import json
try:
    import base58
    with open('$keypair_file') as f:
        kp = json.load(f)
    print(base58.b58encode(bytes(kp[32:])).decode())
except ImportError:
    # Without base58, use solana-keygen
    pass
except:
    pass
" 2>/dev/null || echo ""
    fi
}

get_balance() {
    local pubkey="$1"

    # Try solana CLI
    if command -v solana &>/dev/null; then
        local bal
        bal=$(timeout 5 solana balance "$pubkey" --url "$SOLANA_RPC_URL" 2>/dev/null | grep -oP '[\d.]+') || true
        if [[ -n "$bal" ]]; then
            echo "$bal"
            return
        fi
    fi

    # Fallback to RPC
    local result
    result=$(rpc_call "getBalance" "[\"$pubkey\"]" 5)
    echo "$result" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    lamports = data.get('result', {}).get('value', 0)
    print(f'{lamports / 1e9:.4f}')
except:
    print('0.00')
" 2>/dev/null || echo "0.00"
}

get_account_balance_rest() {
    local pubkey="$1"
    get_balance "$pubkey"
}

# ═══════════════════════════════════════════════════════════════════
# Transaction Functions
# ═══════════════════════════════════════════════════════════════════
get_recent_signatures() {
    local pubkey="$1"
    local limit="${2:-10}"

    rpc_call "getSignaturesForAddress" "[\"$pubkey\",{\"limit\":$limit}]" 10
}

check_transaction() {
    local signature="$1"

    rpc_call "getTransaction" "[\"$signature\",{\"encoding\":\"json\",\"maxSupportedTransactionVersion\":0}]" 10
}

# ═══════════════════════════════════════════════════════════════════
# Pool/AMM Functions — Real On-Chain Data
# ═══════════════════════════════════════════════════════════════════
get_pool_reserves() {
    # Try real on-chain data first via solana_tx module
    if declare -f get_pool_reserves_live &>/dev/null; then
        local live_data
        live_data=$(get_pool_reserves_live 2>/dev/null) || true
        if [[ -n "$live_data" ]] && [[ "$live_data" != "ERROR:"* ]]; then
            echo "$live_data"
            return 0
        fi
    fi

    # Fallback: Try direct vault balance query
    local result
    result=$(rpc_call "getProgramAccounts" \
        "[\"$BASTION_AMM_PROGRAM\",{\"encoding\":\"base64\",\"filters\":[{\"dataSize\":246}]}]" 5 2>/dev/null) || true

    if [[ -n "$result" ]] && echo "$result" | grep -q '"result":\[{' 2>/dev/null; then
        # Parse pool account and get vault balances
        python3 << PYEOF 2>/dev/null
import json, base64, struct, sys

data = json.loads('''$result''')
accounts = data.get('result', [])

if not accounts:
    print("ERROR:NO_POOLS")
    sys.exit(0)

raw = base64.b64decode(accounts[0]['account']['data'][0])
if len(raw) < 200:
    print("ERROR:INVALID_DATA")
    sys.exit(0)

# vault_a at offset 8+96, vault_b at offset 8+128
vault_a = raw[104:136]
vault_b = raw[136:168]

def encode_b58(b):
    alphabet = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'
    n = int.from_bytes(b, 'big')
    r = ''
    while n > 0:
        n, m = divmod(n, 58)
        r = alphabet[m] + r
    return ('1' * sum(1 for x in b if x == 0)) + (r or '1')

print(json.dumps({"vault_a": encode_b58(vault_a), "vault_b": encode_b58(vault_b)}))
PYEOF
        return 0
    fi

    echo "ERROR:CONTRACT_UNAVAILABLE"
    return 1
}

calculate_swap_output() {
    local amount_in="$1"
    local reserve_in="$2"
    local reserve_out="$3"

    # x * y = k formula with 0.3% fee
    python3 -c "
amount_in = float('$amount_in')
reserve_in = float('$reserve_in')
reserve_out = float('$reserve_out')

amount_in_with_fee = amount_in * 0.997
numerator = amount_in_with_fee * reserve_out
denominator = reserve_in + amount_in_with_fee
amount_out = numerator / denominator

print(f'{amount_out:.4f}')
" 2>/dev/null || echo "0"
}

# ═══════════════════════════════════════════════════════════════════
# Airdrop Helper (devnet/localnet only)
# ═══════════════════════════════════════════════════════════════════
request_airdrop() {
    local pubkey="$1"
    local sol_amount="${2:-1}"

    if command -v solana &>/dev/null; then
        solana airdrop "$sol_amount" "$pubkey" --url "$SOLANA_RPC_URL" 2>/dev/null
    else
        local lamports
        lamports=$(python3 -c "print(int($sol_amount * 1e9))" 2>/dev/null) || return 1
        rpc_call "requestAirdrop" "[\"$pubkey\",$lamports]" 10
    fi
}
